### ISSUE TITLE
Marquee stops scrolling

### ISSUE THREAD

**Issue by dtartaglia** [cbess/AutoScrollLabel#50]
Line 285 ff contains:

```
// setup pause delay/loop
if (finished) {
 [self performSelector:@selector(scrollLabelIfNeeded) withObject:nil];
}
```

If the completion block of the animation is called with `finished` equal to `NO`, then the marquee will stop and refuse to start back up. This is something that happens on occasion while the app is running.

**Comment by ccnyou** [comment]
fix the bug mentioned above:

```objective-c
- (void)didMoveToWindow {
    [super didMoveToWindow];
    
    [self scrollLabelIfNeeded];
}
```

**Comment by cbess** [comment]
Applied in commit 9062820

**Comment by cbess** [comment]
Thanks for the code snippet.
