### ISSUE TITLE
How to install pod with Swift

### ISSUE THREAD

**Issue by kylieritchie** [cbess/AutoScrollLabel#65]
I am a beginner at programming, and an extreme beginner at CocoaPods.

https://github.com/cbess/AutoScrollLabel

Trying to figure out how to install this pod. I am using Swift and trying to create something with tvOS. This link says it supports both. Can someone take me through the process of installing the pod.

I have saved the project to my desktop and cd'ed into it, and I don't know wh

**Comment by cbess** [comment]
It's best read the CocoaPods user guide: 
https://guides.cocoapods.org/using/using-cocoapods

Use `AutoScrollLabel` in the `Podfile`. No need to clone the repository.
